### ISSUE TITLE
multipass-js 0.1.6 not published to npm

### ISSUE THREAD

**Issue by davidpaulsson** [softmarshmallow/multipass-js#3]
Thanks for this package, and your time!

Could you publish 0.1.6 to npm? [The latest version there is 0.1.5](https://www.npmjs.com/package/multipass-js) and I'm looking forward to using `.token()` that I see was added in #2.

**Comment by softmarshmallow** [comment]
Ok. just a sec

**Comment by softmarshmallow** [comment]
Done. check please. and close this issue if works fine.

**Comment by softmarshmallow** [comment]
https://www.npmjs.com/package/multipass-js

**Comment by davidpaulsson** [comment]
Lightning-fast! Thanks, works like a charm ✨

**Comment by softmarshmallow** [comment]
Yeah. Fast it was for me too. LOL

Happy coding! and also take a look at my newest project Bridged

https://bridged.xyz
https://github.com/bridgedxyz

in case anyone needs it.'
